### ISSUE TITLE
Can I use this to capture the DynamoDB changes?

### ISSUE THREAD

**Issue by anekar3416** [saidsef/aws-kinesis-local#33]
I have a project in which I have to capture the DynamoDB table change events using the Kinesis Data Streams. Just wondering whether does this support the same?

**Comment by saidsef** [comment]
@anekar3416 this is meant for events storing - so yes, you could use this for your use case you have described.

However, this is designed for local Kinesis instance i.e. test Kenisis locally, for serious workload usage you will have to manage/set memory, cpu and storage requirements to scale it appropriately.  For actual production use I recommend you use the managed AWS Kinesis service.

**Comment by anekar3416** [comment]
@saidsef I am trying the use-case that I have just mentioned above. But what I am seeing is that I am not able to attach the newly created Stream as destination to a DynamoDB table. Facing this below error:

```
An error occurred (UnknownOperationException) when calling the EnableKinesisStreamingDestination operation: An unknown operation was requested.
```

Here are the sequence of operations that I am performing:
1. Start the container - aws-dynamodb-local(https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html#docker). On port 8000
2. Start the aws-kinesis-local container. On port 8001
3. Create a new DDB table:
```
aws dynamodb create-table \
    --table-name Music \
    --attribute-definitions \
        AttributeName=Artist,AttributeType=S \
        AttributeName=SongTitle,AttributeType=S \
    --key-schema \
        AttributeName=Artist,KeyType=HASH \
        AttributeName=SongTitle,KeyType=RANGE \
    --provisioned-throughput \
        ReadCapacityUnits=5,WriteCapacityUnits=5 \
    --table-class STANDARD --endpoint-url=http://localhost:8000
```
4. Create a new stream.
```
aws kinesis create-stream --stream-name samplestream --shard-count 3 --endpoint-url=http://localhost:8001
```
5. Enable the Kinesis streams on the table to capture change events.
```
aws dynamodb enable-kinesis-streaming-destination \
    --table-name Music \
    --stream-arn arn:aws:kinesis:us-east-1:000000000000:stream/samplestream --endpoint-url=http://localhost:8000

An error occurred (UnknownOperationException) when calling the EnableKinesisStreamingDestination operation:
```


Can I get any help on this please?

**Comment by saidsef** [comment]
Hi @anekar3416, looking at your example, you will need to update the Kinesis endpoint to something other than `localhost` - something dynamodb can resolve.

**Comment by saidsef** [comment]
@anekar3416 if there are no more updates I'm going to close this issue.
